In [2]:
import pandas as pd
import numpy as np

Pandas have 2 basic data types, series & DataFrames. series can be considered a column & DataFrame a table


- standard way of creating a series is using a list
- standard way of creating a DataFrame is using a dictionary

In [3]:
roll_num = [221,222,223,224]
roll_series = pd.Series(roll_num, name='Roll numbers')
roll_series

0    221
1    222
2    223
3    224
Name: Roll numbers, dtype: int64

In [4]:
names = ['Himanshu', 'Jay', 'Ken', 'Ron']
name_series = pd.Series(names, name='Names')
name_series

0    Himanshu
1         Jay
2         Ken
3         Ron
Name: Names, dtype: object

creating DataFrames

In [5]:
student_df = pd.DataFrame({'Student Name':['Himanshu', 'Jay', 'Ken', 'Ron'], 'Roll number':[221,222,223,224]})
student_df

  Student Name  Roll number
0     Himanshu          221
1          Jay          222
2          Ken          223
3          Ron          224

In [6]:
student_df1 = pd.DataFrame({'Student Name':names, 'Roll number':roll_num})
student_df1

  Student Name  Roll number
0     Himanshu          221
1          Jay          222
2          Ken          223
3          Ron          224

importing csv files & creating DataFrames

In [7]:
pressing_df = pd.read_csv('datasets/Pressing.csv',index_col=0)
pressing_df

                 Press  Succ     %  Def 3rd  Mid 3rd  Att 3rd
Squad
Arsenal           1869   533  28.5      610      790      469
Aston Villa       1855   558  30.1      584      807      464
Brighton          2033   676  33.3      703      853      477
Burnley           1783   474  26.6      539      847      397
Chelsea           2245   696  31.0      742      975      528
Crystal Palace    2324   653  28.1      928      963      433
Everton           2250   668  29.7      907      928      415
Fulham            1853   549  29.6      633      767      453
Leeds United      2685   872  32.5      940     1148      597
Leicester City    2293   719  31.4      852      929      512
Liverpool         2074   704  33.9      527      847      700
Manchester City   1696   518  30.5      427      765      504
Manchester Utd    2077   633  30.5      643      912      522
Newcastle Utd     2238   559  25.0      889      940      409
Sheffield Utd     2603   673  25.9      871     1086      646
Southampton       2336   757  32.4      755     1051      530
Tottenham         2524   659  26.1      976     1040      508
West Brom         2433   663  27.3      995      989      449
West Ham          2103   599  28.5      824      898      381
Wolves            2030   608  30.0      838      870      322

In [8]:
df_spo = pd.read_csv('datasets\Spotify.csv')

In [9]:
df_spo

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country"
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal"
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Jonas Brothers,Sucker,181026,False,2019,79,0.842,0.734,1,-5.065,0,0.0588,0.0427,0.000000,0.1060,0.952,137.958,pop
1996,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707,1,0.1570,0.1170,0.000021,0.1050,0.564,169.994,pop
1997,Blanco Brown,The Git Up,200593,False,2019,69,0.847,0.678,9,-8.635,1,0.1090,0.0669,0.000000,0.2740,0.811,97.984,"hip hop, country"
1998,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513,1,0.0656,0.4500,0.000002,0.2220,0.347,102.998,pop
1999,Post Malone,Circles,215280,False,2019,85,0.695,0.762,0,-3.497,1,0.0395,0.1920,0.002440,0.0863,0.553,120.042,hip hop

Indexing, selecting & Assigning

In [10]:
df_spo.columns

Index(['artist', 'song', 'duration_ms', 'explicit', 'year', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'genre'],
      dtype='object')

In [11]:
df_spo.energy

0       0.834
1       0.897
2       0.496
3       0.913
4       0.928
        ...
1995    0.734
1996    0.702
1997    0.678
1998    0.520
1999    0.762
Name: energy, Length: 2000, dtype: float64

In [12]:
df_spo['genre'].unique()

array(['pop', 'rock, pop', 'pop, country', 'rock, metal',
       'hip hop, pop, R&B', 'hip hop', 'pop, rock', 'pop, R&B',
       'Dance/Electronic', 'pop, Dance/Electronic',
       'rock, Folk/Acoustic, easy listening', 'metal', 'hip hop, pop',
       'R&B', 'pop, latin', 'Folk/Acoustic, rock',
       'pop, easy listening, Dance/Electronic', 'rock',
       'rock, blues, latin', 'pop, rock, metal', 'rock, pop, metal',
       'hip hop, R&B', 'pop, Folk/Acoustic', 'set()',
       'hip hop, pop, latin', 'hip hop, Dance/Electronic',
       'hip hop, pop, rock', 'World/Traditional, Folk/Acoustic',
       'Folk/Acoustic, pop', 'rock, easy listening',
       'World/Traditional, hip hop', 'hip hop, pop, R&B, latin',
       'rock, blues', 'rock, R&B, Folk/Acoustic, pop', 'latin',
       'pop, R&B, Dance/Electronic', 'World/Traditional, rock',
       'pop, rock, Dance/Electronic', 'pop, easy listening, jazz',
       'rock, Dance/Electronic', 'World/Traditional, pop, Folk/Acoustic',
       'country', 'hip hop, pop, Dance/Electronic',
       'hip hop, pop, country', 'World/Traditional, rock, pop',
       'World/Traditional, pop', 'hip hop, pop, R&B, Dance/Electronic',
       'pop, R&B, easy listening', 'rock, pop, Dance/Electronic',
       'Folk/Acoustic, rock, pop', 'rock, pop, metal, Dance/Electronic',
       'pop, rock, Folk/Acoustic', 'country, latin', 'rock, classical',
       'rock, Folk/Acoustic, pop', 'hip hop, rock, pop', 'easy listening',
       'hip hop, latin, Dance/Electronic', 'hip hop, country'],
      dtype=object)

In [13]:
df_spo['duration_ms'].max()

484146

In [14]:
df_spo['duration_mins'] = df_spo['duration_ms']/60000

In [15]:
df_spo.query('duration_mins == duration_mins.max()')

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
1381,Justin Timberlake,Mirrors,484146,False,2013,78,0.574,0.512,5,-6.664,0,0.0503,0.234,0.0,0.0946,0.512,76.899,pop,8.0691

In [16]:
df_spo[df_spo['artist']=='Rihanna']

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
503,Rihanna,Pon de Replay,246960,False,2005,77,0.779,0.640,7,-8.415,1,0.1590,0.000155,0.000770,0.1010,0.498,99.019,"hip hop, pop, R&B",4.116000
605,Rihanna,SOS,238920,False,2006,73,0.677,0.671,7,-4.905,1,0.0361,0.004000,0.000051,0.4130,0.527,137.046,"hip hop, pop, R&B",3.982000
648,Rihanna,Unfaithful,226973,False,2006,70,0.588,0.391,0,-8.607,0,0.0334,0.839000,0.000000,0.2270,0.349,144.069,"hip hop, pop, R&B",3.782883
701,Rihanna,Umbrella,275986,False,2008,81,0.583,0.829,1,-4.603,1,0.1340,0.008640,0.000000,0.0426,0.575,174.028,"hip hop, pop, R&B",4.599767
726,Rihanna,Shut Up And Drive,212280,False,2008,69,0.735,0.826,1,-4.902,1,0.0349,0.001010,0.129000,0.1970,0.740,132.964,"hip hop, pop, R&B",3.538000
802,Rihanna,Take A Bow,229413,False,2008,74,0.697,0.467,9,-7.536,1,0.0715,0.248000,0.000000,0.0941,0.572,82.082,"hip hop, pop, R&B",3.823550
811,Rihanna,Disturbia,238626,False,2008,76,0.707,0.813,11,-4.515,0,0.0571,0.086300,0.000000,0.1680,0.722,124.921,"hip hop, pop, R&B",3.977100
819,Rihanna,Don't Stop The Music,267080,False,2008,77,0.835,0.669,6,-5.582,0,0.0643,0.033600,0.000069,0.0535,0.542,122.668,"hip hop, pop, R&B",4.451333
935,Rihanna,Russian Roulette,227533,True,2009,64,0.480,0.486,6,-5.754,0,0.0447,0.046000,0.000000,0.1070,0.265,80.051,"hip hop, pop, R&B",3.792217
1007,Rihanna,Only Girl (In The World),235493,False,2010,73,0.789,0.716,11,-4.241,0,0.0432,0.129000,0.000011,0.0690,0.611,125.906,"hip hop, pop, R&B",3.924883
1015,Rihanna,Te Amo,208426,True,2009,67,0.567,0.707,8,-5.455,0,0.0818,0.541000,0.000176,0.1000,0.751,171.917,"hip hop, pop, R&B",3.473767
1024,Rihanna,Rude Boy,222920,True,2009,74,0.563,0.750,11,-4.496,1,0.1270,0.113000,0.000000,0.0788,0.812,173.906,"hip hop, pop, R&B",3.715333
1042,Rihanna,Hard,250600,True,2009,55,0.310,0.746,1,-3.599,1,0.1110,0.012100,0.000000,0.6490,0.163,182.032,"hip hop, pop, R&B",4.176667
1052,Rihanna,Man Down,267000,True,2010,68,0.470,0.904,0,-4.024,0,0.1770,0.043600,0.000000,0.0491,0.557,155.788,"hip hop, pop, R&B",4.450000
1066,Rihanna,What's My Name?,263173,False,2010,66,0.692,0.786,2,-2.959,1,0.0690,0.230000,0.000000,0.0797,0.583,100.025,"hip hop, pop, R&B",4.386217
1109,Rihanna,S&M,243533,False,2010,73,0.767,0.682,1,-5.020,1,0.0420,0.011300,0.000160,0.1040,0.833,127.975,"hip hop, pop, R&B",4.058883
1150,Rihanna,We Found Love,215226,False,2011,75,0.735,0.766,1,-4.485,1,0.0383,0.025000,0.001380,0.1080,0.600,127.985,"hip hop, pop, R&B",3.587100
1158,Rihanna,What's My Name?,263173,False,2010,66,0.692,0.786,2,-2.959,1,0.0690,0.230000,0.000000,0.0797,0.583,100.025,"hip hop, pop, R&B",4.386217
1200,Rihanna,We Found Love,215226,False,2011,75,0.735,0.766,1,-4.485,1,0.0383,0.025000,0.001380,0.1080,0.600,127.985,"hip hop, pop, R&B",3.587100
1208,Rihanna,Where Have You Been,242680,False,2011,71,0.719,0.847,0,-6.340,0,0.0916,0.002010,0.020400,0.2230,0.444,127.963,"hip hop, pop, R&B",4.044667
1230,Rihanna,Diamonds,225146,False,2012,75,0.564,0.710,11,-4.920,0,0.0461,0.001250,0.000000,0.1090,0.393,91.972,"hip hop, pop, R&B",3.752433
1396,Rihanna,Stay,240706,False,2012,76,0.621,0.310,9,-10.164,0,0.0283,0.945000,0.000061,0.1170,0.125,111.893,"hip hop, pop, R&B",4.011767
1539,Rihanna,Bitch Better Have My Money,219305,True,2015,73,0.781,0.728,1,-4.981,1,0.0621,0.050900,0.000002,0.2570,0.395,102.990,"hip hop, pop, R&B",3.655083
1609,Rihanna,Work,219320,True,2016,75,0.725,0.534,11,-6.238,1,0.0946,0.075200,0.000000,0.0919,0.558,91.974,"hip hop, pop, R&B",3.655333
1636,Rihanna,Needed Me,191600,True,2016,80,0.671,0.314,5,-8.091,0,0.2440,0.110000,0.000000,0.0825,0.296,110.898,"hip hop, pop, R&B",3.193333

    -iloc is index based operator
    -loc is label based
    -both take arguments as row first, column second

eg. df.iloc[row_index range, column_index range]

In [17]:
df_spo.iloc[:10, :10] # upto 10th row & 10th column

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806
5,Sisqo,Thong Song,253733,True,1999,69,0.706,0.888,2,-6.959
6,Eminem,The Real Slim Shady,284200,True,2000,86,0.949,0.661,5,-4.244
7,Robbie Williams,Rock DJ,258560,False,2000,68,0.708,0.772,7,-4.264
8,Destiny's Child,Say My Name,271333,False,1999,75,0.713,0.678,5,-3.525
9,Modjo,Lady - Hear Me Tonight,307153,False,2001,77,0.720,0.808,6,-5.627

In [18]:
df_spo.iloc[:5, :] #upto 5th row, all columns

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop,3.519333
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop",2.784433
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country",4.175767
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal",3.741550
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop,3.342667

In [19]:
df_spo.iloc[:, :3] #all rows, upto 3 columns

              artist                                    song  duration_ms
0     Britney Spears                  Oops!...I Did It Again       211160
1          blink-182                    All The Small Things       167066
2         Faith Hill                                 Breathe       250546
3           Bon Jovi                            It's My Life       224493
4             *NSYNC                             Bye Bye Bye       200560
...              ...                                     ...          ...
1995  Jonas Brothers                                  Sucker       181026
1996    Taylor Swift                            Cruel Summer       178426
1997    Blanco Brown                              The Git Up       200593
1998       Sam Smith  Dancing With A Stranger (with Normani)       171029
1999     Post Malone                                 Circles       215280

[2000 rows x 3 columns]

In [20]:
df_spo.iloc[[1,3,5], [1,2,4,6]] #custom rows & columns

                   song  duration_ms  year  danceability
1  All The Small Things       167066  1999         0.434
3          It's My Life       224493  2000         0.551
5            Thong Song       253733  1999         0.706

In [21]:
df_spo.iloc[-5:, -5:] #last 5 columns & last 5 rows

      liveness  valence    tempo             genre  duration_mins
1995    0.1060    0.952  137.958               pop       3.017100
1996    0.1050    0.564  169.994               pop       2.973767
1997    0.2740    0.811   97.984  hip hop, country       3.343217
1998    0.2220    0.347  102.998               pop       2.850483
1999    0.0863    0.553  120.042           hip hop       3.588000

loc is strictly column name based

In [22]:
df_spo.loc[:, 'tempo'] #all rows, specific column

0        95.053
1       148.726
2       136.859
3       119.992
4       172.656
         ...
1995    137.958
1996    169.994
1997     97.984
1998    102.998
1999    120.042
Name: tempo, Length: 2000, dtype: float64

In [23]:
df_spo.loc[:10, ['artist', 'duration_mins']] #10 rows, specific columns

             artist  duration_mins
0    Britney Spears       3.519333
1         blink-182       2.784433
2        Faith Hill       4.175767
3          Bon Jovi       3.741550
4            *NSYNC       3.342667
5             Sisqo       4.228883
6            Eminem       4.736667
7   Robbie Williams       4.309333
8   Destiny's Child       4.522217
9             Modjo       5.119217
10  Gigi D'Agostino       3.979317

In [24]:
df_spo.loc[(df_spo['artist']=='Rihanna') & (df_spo['year'] == 2008)]

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
701,Rihanna,Umbrella,275986,False,2008,81,0.583,0.829,1,-4.603,1,0.1340,0.00864,0.000000,0.0426,0.575,174.028,"hip hop, pop, R&B",4.599767
726,Rihanna,Shut Up And Drive,212280,False,2008,69,0.735,0.826,1,-4.902,1,0.0349,0.00101,0.129000,0.1970,0.740,132.964,"hip hop, pop, R&B",3.538000
802,Rihanna,Take A Bow,229413,False,2008,74,0.697,0.467,9,-7.536,1,0.0715,0.24800,0.000000,0.0941,0.572,82.082,"hip hop, pop, R&B",3.823550
811,Rihanna,Disturbia,238626,False,2008,76,0.707,0.813,11,-4.515,0,0.0571,0.08630,0.000000,0.1680,0.722,124.921,"hip hop, pop, R&B",3.977100
819,Rihanna,Don't Stop The Music,267080,False,2008,77,0.835,0.669,6,-5.582,0,0.0643,0.03360,0.000069,0.0535,0.542,122.668,"hip hop, pop, R&B",4.451333

In [25]:
df_spo.loc[(df_spo['genre'].isin(['rock', 'pop']))]

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop,3.519333
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop,3.342667
10,Gigi D'Agostino,L'Amour Toujours,238759,False,2011,1,0.617,0.728,7,-7.932,1,0.0292,0.0328,0.048200,0.3600,0.808,139.066,pop,3.979317
11,Eiffel 65,Move Your Body - Gabry Ponte Original Radio Edit,268863,False,1999,56,0.745,0.958,7,-9.664,1,0.0287,0.0813,0.324000,0.5330,0.960,129.962,pop,4.481050
12,Bomfunk MC's,Freestyler,306333,False,2000,55,0.822,0.922,11,-5.798,0,0.0989,0.0291,0.325000,0.2520,0.568,163.826,pop,5.105550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,Panic! At The Disco,High Hopes,190946,False,2018,80,0.579,0.904,5,-2.729,1,0.0618,0.1930,0.000000,0.0640,0.681,82.014,rock,3.182433
1990,Sam Smith,How Do You Sleep?,202204,False,2019,73,0.477,0.682,1,-4.931,0,0.0925,0.1530,0.000000,0.0763,0.345,110.567,pop,3.370067
1995,Jonas Brothers,Sucker,181026,False,2019,79,0.842,0.734,1,-5.065,0,0.0588,0.0427,0.000000,0.1060,0.952,137.958,pop,3.017100
1996,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707,1,0.1570,0.1170,0.000021,0.1050,0.564,169.994,pop,2.973767
1998,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513,1,0.0656,0.4500,0.000002,0.2220,0.347,102.998,pop,2.850483

In [26]:
df_spo.artist

0       Britney Spears
1            blink-182
2           Faith Hill
3             Bon Jovi
4               *NSYNC
             ...
1995    Jonas Brothers
1996      Taylor Swift
1997      Blanco Brown
1998         Sam Smith
1999       Post Malone
Name: artist, Length: 2000, dtype: object

In [27]:
df_spo.artist.map(lambda p:p.upper())

0       BRITNEY SPEARS
1            BLINK-182
2           FAITH HILL
3             BON JOVI
4               *NSYNC
             ...
1995    JONAS BROTHERS
1996      TAYLOR SWIFT
1997      BLANCO BROWN
1998         SAM SMITH
1999       POST MALONE
Name: artist, Length: 2000, dtype: object

map function applies one operation to numerous values 


lambda is a shortened way to use a function

In [28]:
df_spo.genre.map(lambda p:p.upper())

0                    POP
1              ROCK, POP
2           POP, COUNTRY
3            ROCK, METAL
4                    POP
              ...
1995                 POP
1996                 POP
1997    HIP HOP, COUNTRY
1998                 POP
1999             HIP HOP
Name: genre, Length: 2000, dtype: object

map returns a series


syntax: df.column.map(function) function will applied on each value of that column

In [29]:
df_spo.genre.value_counts()

pop                                      428
hip hop, pop                             277
hip hop, pop, R&B                        244
pop, Dance/Electronic                    221
pop, R&B                                 178
hip hop                                  124
hip hop, pop, Dance/Electronic            78
rock                                      58
rock, pop                                 43
Dance/Electronic                          41
rock, metal                               38
pop, latin                                28
pop, rock                                 26
set()                                     22
hip hop, Dance/Electronic                 16
latin                                     15
pop, rock, metal                          14
hip hop, pop, latin                       14
R&B                                       13
pop, rock, Dance/Electronic               13
country                                   10
metal                                      9
hip hop, pop, rock                         9
rock, pop, Dance/Electronic                8
pop, Folk/Acoustic                         8
pop, country                               8
pop, R&B, Dance/Electronic                 6
rock, pop, metal                           4
hip hop, pop, R&B, Dance/Electronic        3
hip hop, R&B                               3
hip hop, pop, R&B, latin                   3
World/Traditional, pop, Folk/Acoustic      2
pop, rock, Folk/Acoustic                   2
pop, easy listening, jazz                  2
World/Traditional, rock                    2
rock, blues, latin                         2
World/Traditional, rock, pop               2
hip hop, rock, pop                         2
rock, blues                                2
Folk/Acoustic, pop                         2
World/Traditional, hip hop                 2
rock, pop, metal, Dance/Electronic         1
rock, classical                            1
country, latin                             1
hip hop, latin, Dance/Electronic           1
rock, Folk/Acoustic, pop                   1
easy listening                             1
Folk/Acoustic, rock, pop                   1
rock, easy listening                       1
pop, R&B, easy listening                   1
World/Traditional, pop                     1
hip hop, pop, country                      1
rock, Dance/Electronic                     1
rock, R&B, Folk/Acoustic, pop              1
World/Traditional, Folk/Acoustic           1
pop, easy listening, Dance/Electronic      1
Folk/Acoustic, rock                        1
rock, Folk/Acoustic, easy listening        1
hip hop, country                           1
Name: genre, dtype: int64

In [30]:
df_spo['artist'].value_counts()

Rihanna           25
Drake             23
Eminem            21
Calvin Harris     20
Britney Spears    19
                  ..
Sidney Samson      1
Cam’ron            1
Elvis Presley      1
Lucenzo            1
Blanco Brown       1
Name: artist, Length: 835, dtype: int64

In [31]:
df_spo.loc[(df_spo.artist == 'Calvin Harris')]

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
745,Calvin Harris,Acceptable in the 80's,333680,False,2007,57,0.787,0.808,7,-5.454,1,0.0511,0.014300,0.257000,0.0466,0.942,127.990,"hip hop, pop, Dance/Electronic",5.561333
968,Calvin Harris,I'm Not Alone - Radio Edit,210973,False,2009,55,0.597,0.684,7,-6.614,1,0.0321,0.004810,0.105000,0.3170,0.435,130.990,"hip hop, pop, Dance/Electronic",3.516217
1169,Calvin Harris,Bounce (feat. Kelis) - Radio Edit,222186,False,2012,62,0.779,0.963,2,-2.125,0,0.0399,0.033400,0.493000,0.6640,0.759,127.941,"hip hop, pop, Dance/Electronic",3.703100
1244,Calvin Harris,Feel So Close - Radio Edit,206413,False,2012,79,0.707,0.924,7,-2.842,1,0.0310,0.000972,0.007030,0.2040,0.919,127.937,"hip hop, pop, Dance/Electronic",3.440217
1251,Calvin Harris,Let's Go (feat. Ne-Yo),232800,False,2012,66,0.710,0.882,4,-2.932,0,0.0595,0.007770,0.007710,0.2940,0.875,128.016,"hip hop, pop, Dance/Electronic",3.880000
1277,Calvin Harris,We'll Be Coming Back (feat. Example),234360,False,2012,62,0.596,0.952,7,-4.364,1,0.0873,0.001310,0.000000,0.5980,0.571,127.945,"hip hop, pop, Dance/Electronic",3.906000
1347,Calvin Harris,Drinking from the Bottle (feat. Tinie Tempah),240346,False,2012,61,0.665,0.886,9,-4.175,0,0.0514,0.046900,0.000062,0.0525,0.530,128.062,"hip hop, pop, Dance/Electronic",4.005767
1353,Calvin Harris,I Need Your Love (feat. Ellie Goulding),234506,False,2012,70,0.695,0.869,8,-5.066,1,0.0483,0.410000,0.000000,0.2370,0.580,124.989,"hip hop, pop, Dance/Electronic",3.908433
1359,Calvin Harris,Sweet Nothing (feat. Florence Welch),212560,False,2012,71,0.573,0.929,8,-3.942,0,0.1090,0.197000,0.000112,0.0567,0.582,127.934,"hip hop, pop, Dance/Electronic",3.542667
1369,Calvin Harris,Thinking About You (feat. Ayah Marar),247933,False,2012,65,0.725,0.874,0,-3.715,0,0.0396,0.002620,0.000412,0.0958,0.748,127.985,"hip hop, pop, Dance/Electronic",4.132217
1423,Calvin Harris,Under Control (feat. Hurts),184280,False,2014,72,0.544,0.915,8,-3.405,1,0.0841,0.129000,0.000914,0.1150,0.510,126.094,"hip hop, pop, Dance/Electronic",3.071333
1429,Calvin Harris,Blame (feat. John Newman),212960,False,2014,75,0.414,0.857,0,-4.078,0,0.0808,0.028700,0.005740,0.3430,0.348,128.024,"hip hop, pop, Dance/Electronic",3.549333
1434,Calvin Harris,Summer,224506,False,2014,21,0.603,0.861,4,-3.565,0,0.0325,0.021500,0.043000,0.1000,0.720,127.962,"hip hop, pop, Dance/Electronic",3.741767
1507,Calvin Harris,Outside (feat. Ellie Goulding),227266,False,2014,78,0.646,0.823,2,-4.123,0,0.0394,0.213000,0.000000,0.3220,0.418,128.035,"hip hop, pop, Dance/Electronic",3.787767
1521,Calvin Harris,How Deep Is Your Love,212640,False,2015,76,0.738,0.868,11,-4.373,0,0.0731,0.039200,0.001690,0.3880,0.336,122.003,"hip hop, pop, Dance/Electronic",3.544000
1633,Calvin Harris,This Is What You Came For (feat. Rihanna),222160,False,2016,79,0.631,0.927,9,-2.787,0,0.0332,0.199000,0.119000,0.1480,0.465,123.962,"hip hop, pop, Dance/Electronic",3.702667
1641,Calvin Harris,My Way,219159,False,2016,74,0.818,0.913,4,-3.060,0,0.0426,0.093000,0.000037,0.1610,0.536,119.986,"hip hop, pop, Dance/Electronic",3.652650
1774,Calvin Harris,"Feels (feat. Pharrell Williams, Katy Perry & B...",223413,True,2017,79,0.893,0.745,11,-3.105,0,0.0571,0.064200,0.000000,0.0943,0.872,101.018,"hip hop, pop, Dance/Electronic",3.723550
1812,Calvin Harris,One Kiss (with Dua Lipa),214846,False,2018,81,0.791,0.862,9,-3.240,0,0.1100,0.037000,0.000022,0.0814,0.592,123.994,"hip hop, pop, Dance/Electronic",3.580767
1954,Calvin Harris,Giant (with Rag'n'Bone Man),229184,False,2019,73,0.807,0.887,1,-4.311,0,0.0361,0.016000,0.000503,0.0811,0.606,122.015,"hip hop, pop, Dance/Electronic",3.819733

In [32]:
df_spo.describe()

,duration_ms,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_mins
count,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,228748.124500,2009.49400,59.872500,0.667437,0.720366,5.378000,-5.512435,0.553500,0.103568,0.128955,0.015226,0.181216,0.551690,120.122558,3.812469
std,39136.569008,5.85996,21.335577,0.140416,0.152745,3.615059,1.933482,0.497254,0.096159,0.173346,0.087771,0.140669,0.220864,26.967112,0.652276
min,113000.000000,1998.00000,0.000000,0.129000,0.054900,0.000000,-20.514000,0.000000,0.023200,0.000019,0.000000,0.021500,0.038100,60.019000,1.883333
25%,203580.000000,2004.00000,56.000000,0.581000,0.622000,2.000000,-6.490250,0.000000,0.039600,0.014000,0.000000,0.088100,0.386750,98.985750,3.393000
50%,223279.500000,2010.00000,65.500000,0.676000,0.736000,6.000000,-5.285000,1.000000,0.059850,0.055700,0.000000,0.124000,0.557500,120.021500,3.721325
75%,248133.000000,2015.00000,73.000000,0.764000,0.839000,8.000000,-4.167750,1.000000,0.129000,0.176250,0.000068,0.241000,0.730000,134.265500,4.135550
max,484146.000000,2020.00000,89.000000,0.975000,0.999000,11.000000,-0.276000,1.000000,0.576000,0.976000,0.985000,0.853000,0.973000,210.851000,8.069100

In [33]:
df_spo.head()

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop,3.519333
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop",2.784433
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country",4.175767
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal",3.741550
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop,3.342667

In [34]:
df_spo.tail()

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
1995,Jonas Brothers,Sucker,181026,False,2019,79,0.842,0.734,1,-5.065,0,0.0588,0.0427,0.000000,0.1060,0.952,137.958,pop,3.017100
1996,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707,1,0.1570,0.1170,0.000021,0.1050,0.564,169.994,pop,2.973767
1997,Blanco Brown,The Git Up,200593,False,2019,69,0.847,0.678,9,-8.635,1,0.1090,0.0669,0.000000,0.2740,0.811,97.984,"hip hop, country",3.343217
1998,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513,1,0.0656,0.4500,0.000002,0.2220,0.347,102.998,pop,2.850483
1999,Post Malone,Circles,215280,False,2019,85,0.695,0.762,0,-3.497,1,0.0395,0.1920,0.002440,0.0863,0.553,120.042,hip hop,3.588000

In [35]:
longest = df_spo.duration_ms.idxmax() #index at which duration_ms has highest value

In [36]:
df_spo.loc[longest, 'song']

'Mirrors'

idxmax returns the index of highest value in a series

In [37]:
shortest = df_spo.duration_ms.idxmin()

In [38]:
df_spo.loc[shortest, 'song']

'Old Town Road'

In [39]:
dfw = pd.read_csv('Datasets\Winemag1.csv',index_col=0)

In [40]:
dfw.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [41]:
dfw.description

0         This tremendous 100% varietal wine hails from ...
1         Ripe aromas of fig, blackberry and cassis are ...
2         Mac Watson honors the memory of a wine once ma...
3         This spent 20 months in 30% new French oak, an...
4         This is the top wine from La Bégude, named aft...
                                ...
150925    Many people feel Fiano represents southern Ita...
150926    Offers an intriguing nose with ginger, lime an...
150927    This classic example comes from a cru vineyard...
150928    A perfect salmon shade, with scents of peaches...
150929    More Pinot Grigios should taste like this. A r...
Name: description, Length: 150930, dtype: object

In [42]:
fruity = dfw.description.map(lambda p: 'fruity' in p).sum()

In [43]:
tropical = dfw.description.map(lambda p: 'tropical' in p).sum()

In [44]:
descriptor_counts = pd.Series([fruity, tropical])
descriptor_counts

0    8669
1    4135
dtype: int64

In [45]:
dfw.points

0         96
1         96
2         96
3         96
4         95
          ..
150925    91
150926    91
150927    91
150928    90
150929    90
Name: points, Length: 150930, dtype: int64

In [46]:
dfw.points.apply(np.sqrt) #apply is equivalent to map

0         9.797959
1         9.797959
2         9.797959
3         9.797959
4         9.746794
            ...
150925    9.539392
150926    9.539392
150927    9.539392
150928    9.486833
150929    9.486833
Name: points, Length: 150930, dtype: float64

In [47]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [48]:
df.apply(np.sum, axis=1) #columnwise addition

0     6
1    15
2    24
dtype: int64

In [49]:
df.apply(np.sum, axis=0) #row-wise addition

A    12
B    15
C    18
dtype: int64

axis=0 for rows

axis=1 for cols

In [50]:
df.apply(lambda p:(p*10).sum(),axis=1)

0     60
1    150
2    240
dtype: int64

In [51]:
df.apply(lambda p:(p*10).sum(),axis=0)

A    120
B    150
C    180
dtype: int64

In [52]:
dfw.points

0         96
1         96
2         96
3         96
4         95
          ..
150925    91
150926    91
150927    91
150928    90
150929    90
Name: points, Length: 150930, dtype: int64

In [53]:
r_mean = dfw.points.mean()
def adjust(r):
    r.points = r.points - r_mean
    return r

dfw.apply(adjust,axis=1).head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,8.111582,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,8.111582,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,8.111582,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,8.111582,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,7.111582,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [55]:
dfw.describe()

              points          price
count  150930.000000  137235.000000
mean       87.888418      33.131482
std         3.222392      36.322536
min        80.000000       4.000000
25%        86.000000      16.000000
50%        88.000000      24.000000
75%        90.000000      40.000000
max       100.000000    2300.000000