In [1]:
import pandas as pd

Pandas have 2 basic data types, series & DataFrames. series can be considered a column & DataFrame a table


- standard way of creating a series is using a list
- standard way of creating a DataFrame is using a dictionary

In [2]:
roll_num = [221,222,223,224]
roll_series = pd.Series(roll_num, name='Roll numbers')
roll_series

0    221
1    222
2    223
3    224
Name: Roll numbers, dtype: int64

In [3]:
names = ['Himanshu', 'Jay', 'Ken', 'Ron']
name_series = pd.Series(names, name='Names')
name_series

0    Himanshu
1         Jay
2         Ken
3         Ron
Name: Names, dtype: object

creating DataFrames

In [4]:
student_df = pd.DataFrame({'Student Name':['Himanshu', 'Jay', 'Ken', 'Ron'], 'Roll number':[221,222,223,224]})
student_df

  Student Name  Roll number
0     Himanshu          221
1          Jay          222
2          Ken          223
3          Ron          224

In [5]:
student_df1 = pd.DataFrame({'Student Name':names, 'Roll number':roll_num})
student_df1

  Student Name  Roll number
0     Himanshu          221
1          Jay          222
2          Ken          223
3          Ron          224

importing csv files & creating DataFrames

In [6]:
pressing_df = pd.read_csv('datasets/Pressing.csv',index_col=0)
pressing_df

                 Press  Succ     %  Def 3rd  Mid 3rd  Att 3rd
Squad
Arsenal           1869   533  28.5      610      790      469
Aston Villa       1855   558  30.1      584      807      464
Brighton          2033   676  33.3      703      853      477
Burnley           1783   474  26.6      539      847      397
Chelsea           2245   696  31.0      742      975      528
Crystal Palace    2324   653  28.1      928      963      433
Everton           2250   668  29.7      907      928      415
Fulham            1853   549  29.6      633      767      453
Leeds United      2685   872  32.5      940     1148      597
Leicester City    2293   719  31.4      852      929      512
Liverpool         2074   704  33.9      527      847      700
Manchester City   1696   518  30.5      427      765      504
Manchester Utd    2077   633  30.5      643      912      522
Newcastle Utd     2238   559  25.0      889      940      409
Sheffield Utd     2603   673  25.9      871     1086      646
Southampton       2336   757  32.4      755     1051      530
Tottenham         2524   659  26.1      976     1040      508
West Brom         2433   663  27.3      995      989      449
West Ham          2103   599  28.5      824      898      381
Wolves            2030   608  30.0      838      870      322

In [7]:
df_spo = pd.read_csv('datasets\Spotify.csv')

In [8]:
df_spo

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country"
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal"
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Jonas Brothers,Sucker,181026,False,2019,79,0.842,0.734,1,-5.065,0,0.0588,0.0427,0.000000,0.1060,0.952,137.958,pop
1996,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707,1,0.1570,0.1170,0.000021,0.1050,0.564,169.994,pop
1997,Blanco Brown,The Git Up,200593,False,2019,69,0.847,0.678,9,-8.635,1,0.1090,0.0669,0.000000,0.2740,0.811,97.984,"hip hop, country"
1998,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513,1,0.0656,0.4500,0.000002,0.2220,0.347,102.998,pop
1999,Post Malone,Circles,215280,False,2019,85,0.695,0.762,0,-3.497,1,0.0395,0.1920,0.002440,0.0863,0.553,120.042,hip hop

Indexing, selecting & Assigning

In [9]:
df_spo.columns

Index(['artist', 'song', 'duration_ms', 'explicit', 'year', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'genre'],
      dtype='object')

In [10]:
df_spo.energy

0       0.834
1       0.897
2       0.496
3       0.913
4       0.928
        ...
1995    0.734
1996    0.702
1997    0.678
1998    0.520
1999    0.762
Name: energy, Length: 2000, dtype: float64

In [11]:
df_spo['genre'].unique()

array(['pop', 'rock, pop', 'pop, country', 'rock, metal',
       'hip hop, pop, R&B', 'hip hop', 'pop, rock', 'pop, R&B',
       'Dance/Electronic', 'pop, Dance/Electronic',
       'rock, Folk/Acoustic, easy listening', 'metal', 'hip hop, pop',
       'R&B', 'pop, latin', 'Folk/Acoustic, rock',
       'pop, easy listening, Dance/Electronic', 'rock',
       'rock, blues, latin', 'pop, rock, metal', 'rock, pop, metal',
       'hip hop, R&B', 'pop, Folk/Acoustic', 'set()',
       'hip hop, pop, latin', 'hip hop, Dance/Electronic',
       'hip hop, pop, rock', 'World/Traditional, Folk/Acoustic',
       'Folk/Acoustic, pop', 'rock, easy listening',
       'World/Traditional, hip hop', 'hip hop, pop, R&B, latin',
       'rock, blues', 'rock, R&B, Folk/Acoustic, pop', 'latin',
       'pop, R&B, Dance/Electronic', 'World/Traditional, rock',
       'pop, rock, Dance/Electronic', 'pop, easy listening, jazz',
       'rock, Dance/Electronic', 'World/Traditional, pop, Folk/Acoustic',
       'country', 'hip hop, pop, Dance/Electronic',
       'hip hop, pop, country', 'World/Traditional, rock, pop',
       'World/Traditional, pop', 'hip hop, pop, R&B, Dance/Electronic',
       'pop, R&B, easy listening', 'rock, pop, Dance/Electronic',
       'Folk/Acoustic, rock, pop', 'rock, pop, metal, Dance/Electronic',
       'pop, rock, Folk/Acoustic', 'country, latin', 'rock, classical',
       'rock, Folk/Acoustic, pop', 'hip hop, rock, pop', 'easy listening',
       'hip hop, latin, Dance/Electronic', 'hip hop, country'],
      dtype=object)

In [12]:
df_spo['duration_ms'].max()

484146

In [13]:
df_spo['duration_mins'] = df_spo['duration_ms']/60000

In [14]:
df_spo.query('duration_mins == duration_mins.max()')

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
1381,Justin Timberlake,Mirrors,484146,False,2013,78,0.574,0.512,5,-6.664,0,0.0503,0.234,0.0,0.0946,0.512,76.899,pop,8.0691

In [15]:
df_spo[df_spo['artist']=='Rihanna']

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
503,Rihanna,Pon de Replay,246960,False,2005,77,0.779,0.640,7,-8.415,1,0.1590,0.000155,0.000770,0.1010,0.498,99.019,"hip hop, pop, R&B",4.116000
605,Rihanna,SOS,238920,False,2006,73,0.677,0.671,7,-4.905,1,0.0361,0.004000,0.000051,0.4130,0.527,137.046,"hip hop, pop, R&B",3.982000
648,Rihanna,Unfaithful,226973,False,2006,70,0.588,0.391,0,-8.607,0,0.0334,0.839000,0.000000,0.2270,0.349,144.069,"hip hop, pop, R&B",3.782883
701,Rihanna,Umbrella,275986,False,2008,81,0.583,0.829,1,-4.603,1,0.1340,0.008640,0.000000,0.0426,0.575,174.028,"hip hop, pop, R&B",4.599767
726,Rihanna,Shut Up And Drive,212280,False,2008,69,0.735,0.826,1,-4.902,1,0.0349,0.001010,0.129000,0.1970,0.740,132.964,"hip hop, pop, R&B",3.538000
802,Rihanna,Take A Bow,229413,False,2008,74,0.697,0.467,9,-7.536,1,0.0715,0.248000,0.000000,0.0941,0.572,82.082,"hip hop, pop, R&B",3.823550
811,Rihanna,Disturbia,238626,False,2008,76,0.707,0.813,11,-4.515,0,0.0571,0.086300,0.000000,0.1680,0.722,124.921,"hip hop, pop, R&B",3.977100
819,Rihanna,Don't Stop The Music,267080,False,2008,77,0.835,0.669,6,-5.582,0,0.0643,0.033600,0.000069,0.0535,0.542,122.668,"hip hop, pop, R&B",4.451333
935,Rihanna,Russian Roulette,227533,True,2009,64,0.480,0.486,6,-5.754,0,0.0447,0.046000,0.000000,0.1070,0.265,80.051,"hip hop, pop, R&B",3.792217
1007,Rihanna,Only Girl (In The World),235493,False,2010,73,0.789,0.716,11,-4.241,0,0.0432,0.129000,0.000011,0.0690,0.611,125.906,"hip hop, pop, R&B",3.924883
1015,Rihanna,Te Amo,208426,True,2009,67,0.567,0.707,8,-5.455,0,0.0818,0.541000,0.000176,0.1000,0.751,171.917,"hip hop, pop, R&B",3.473767
1024,Rihanna,Rude Boy,222920,True,2009,74,0.563,0.750,11,-4.496,1,0.1270,0.113000,0.000000,0.0788,0.812,173.906,"hip hop, pop, R&B",3.715333
1042,Rihanna,Hard,250600,True,2009,55,0.310,0.746,1,-3.599,1,0.1110,0.012100,0.000000,0.6490,0.163,182.032,"hip hop, pop, R&B",4.176667
1052,Rihanna,Man Down,267000,True,2010,68,0.470,0.904,0,-4.024,0,0.1770,0.043600,0.000000,0.0491,0.557,155.788,"hip hop, pop, R&B",4.450000
1066,Rihanna,What's My Name?,263173,False,2010,66,0.692,0.786,2,-2.959,1,0.0690,0.230000,0.000000,0.0797,0.583,100.025,"hip hop, pop, R&B",4.386217
1109,Rihanna,S&M,243533,False,2010,73,0.767,0.682,1,-5.020,1,0.0420,0.011300,0.000160,0.1040,0.833,127.975,"hip hop, pop, R&B",4.058883
1150,Rihanna,We Found Love,215226,False,2011,75,0.735,0.766,1,-4.485,1,0.0383,0.025000,0.001380,0.1080,0.600,127.985,"hip hop, pop, R&B",3.587100
1158,Rihanna,What's My Name?,263173,False,2010,66,0.692,0.786,2,-2.959,1,0.0690,0.230000,0.000000,0.0797,0.583,100.025,"hip hop, pop, R&B",4.386217
1200,Rihanna,We Found Love,215226,False,2011,75,0.735,0.766,1,-4.485,1,0.0383,0.025000,0.001380,0.1080,0.600,127.985,"hip hop, pop, R&B",3.587100
1208,Rihanna,Where Have You Been,242680,False,2011,71,0.719,0.847,0,-6.340,0,0.0916,0.002010,0.020400,0.2230,0.444,127.963,"hip hop, pop, R&B",4.044667
1230,Rihanna,Diamonds,225146,False,2012,75,0.564,0.710,11,-4.920,0,0.0461,0.001250,0.000000,0.1090,0.393,91.972,"hip hop, pop, R&B",3.752433
1396,Rihanna,Stay,240706,False,2012,76,0.621,0.310,9,-10.164,0,0.0283,0.945000,0.000061,0.1170,0.125,111.893,"hip hop, pop, R&B",4.011767
1539,Rihanna,Bitch Better Have My Money,219305,True,2015,73,0.781,0.728,1,-4.981,1,0.0621,0.050900,0.000002,0.2570,0.395,102.990,"hip hop, pop, R&B",3.655083
1609,Rihanna,Work,219320,True,2016,75,0.725,0.534,11,-6.238,1,0.0946,0.075200,0.000000,0.0919,0.558,91.974,"hip hop, pop, R&B",3.655333
1636,Rihanna,Needed Me,191600,True,2016,80,0.671,0.314,5,-8.091,0,0.2440,0.110000,0.000000,0.0825,0.296,110.898,"hip hop, pop, R&B",3.193333

    -iloc is index based operator
    -loc is label based
    -both take arguments as row first, column second

eg. df.iloc[row_index range, column_index range]

In [17]:
df_spo.iloc[:10, :10] # upto 10th row & 10th column

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806
5,Sisqo,Thong Song,253733,True,1999,69,0.706,0.888,2,-6.959
6,Eminem,The Real Slim Shady,284200,True,2000,86,0.949,0.661,5,-4.244
7,Robbie Williams,Rock DJ,258560,False,2000,68,0.708,0.772,7,-4.264
8,Destiny's Child,Say My Name,271333,False,1999,75,0.713,0.678,5,-3.525
9,Modjo,Lady - Hear Me Tonight,307153,False,2001,77,0.720,0.808,6,-5.627

In [19]:
df_spo.iloc[:5, :] #upto 5th row, all columns

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop,3.519333
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop",2.784433
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country",4.175767
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal",3.741550
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop,3.342667

In [23]:
df_spo.iloc[:, :3] #all rows, upto 3 columns

              artist                                    song  duration_ms
0     Britney Spears                  Oops!...I Did It Again       211160
1          blink-182                    All The Small Things       167066
2         Faith Hill                                 Breathe       250546
3           Bon Jovi                            It's My Life       224493
4             *NSYNC                             Bye Bye Bye       200560
...              ...                                     ...          ...
1995  Jonas Brothers                                  Sucker       181026
1996    Taylor Swift                            Cruel Summer       178426
1997    Blanco Brown                              The Git Up       200593
1998       Sam Smith  Dancing With A Stranger (with Normani)       171029
1999     Post Malone                                 Circles       215280

[2000 rows x 3 columns]

In [27]:
df_spo.iloc[[1,3,5], [1,2,4,6]] #custom rows & columns

                   song  duration_ms  year  danceability
1  All The Small Things       167066  1999         0.434
3          It's My Life       224493  2000         0.551
5            Thong Song       253733  1999         0.706

In [30]:
df_spo.iloc[-5:, -5:] #last 5 columns & last 5 rows

      liveness  valence    tempo             genre  duration_mins
1995    0.1060    0.952  137.958               pop       3.017100
1996    0.1050    0.564  169.994               pop       2.973767
1997    0.2740    0.811   97.984  hip hop, country       3.343217
1998    0.2220    0.347  102.998               pop       2.850483
1999    0.0863    0.553  120.042           hip hop       3.588000

loc is strictly column name based

In [32]:
df_spo.loc[:, 'tempo'] #all rows, specific column

0        95.053
1       148.726
2       136.859
3       119.992
4       172.656
         ...
1995    137.958
1996    169.994
1997     97.984
1998    102.998
1999    120.042
Name: tempo, Length: 2000, dtype: float64

In [34]:
df_spo.loc[:10, ['artist', 'duration_mins']] #10 rows, specific columns

             artist  duration_mins
0    Britney Spears       3.519333
1         blink-182       2.784433
2        Faith Hill       4.175767
3          Bon Jovi       3.741550
4            *NSYNC       3.342667
5             Sisqo       4.228883
6            Eminem       4.736667
7   Robbie Williams       4.309333
8   Destiny's Child       4.522217
9             Modjo       5.119217
10  Gigi D'Agostino       3.979317

In [37]:
df_spo.loc[(df_spo['artist']=='Rihanna') & (df_spo['year'] == 2008)]

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
701,Rihanna,Umbrella,275986,False,2008,81,0.583,0.829,1,-4.603,1,0.1340,0.00864,0.000000,0.0426,0.575,174.028,"hip hop, pop, R&B",4.599767
726,Rihanna,Shut Up And Drive,212280,False,2008,69,0.735,0.826,1,-4.902,1,0.0349,0.00101,0.129000,0.1970,0.740,132.964,"hip hop, pop, R&B",3.538000
802,Rihanna,Take A Bow,229413,False,2008,74,0.697,0.467,9,-7.536,1,0.0715,0.24800,0.000000,0.0941,0.572,82.082,"hip hop, pop, R&B",3.823550
811,Rihanna,Disturbia,238626,False,2008,76,0.707,0.813,11,-4.515,0,0.0571,0.08630,0.000000,0.1680,0.722,124.921,"hip hop, pop, R&B",3.977100
819,Rihanna,Don't Stop The Music,267080,False,2008,77,0.835,0.669,6,-5.582,0,0.0643,0.03360,0.000069,0.0535,0.542,122.668,"hip hop, pop, R&B",4.451333

In [42]:
df_spo.loc[(df_spo['genre'].isin(['rock', 'pop']))]

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre,duration_mins
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop,3.519333
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop,3.342667
10,Gigi D'Agostino,L'Amour Toujours,238759,False,2011,1,0.617,0.728,7,-7.932,1,0.0292,0.0328,0.048200,0.3600,0.808,139.066,pop,3.979317
11,Eiffel 65,Move Your Body - Gabry Ponte Original Radio Edit,268863,False,1999,56,0.745,0.958,7,-9.664,1,0.0287,0.0813,0.324000,0.5330,0.960,129.962,pop,4.481050
12,Bomfunk MC's,Freestyler,306333,False,2000,55,0.822,0.922,11,-5.798,0,0.0989,0.0291,0.325000,0.2520,0.568,163.826,pop,5.105550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,Panic! At The Disco,High Hopes,190946,False,2018,80,0.579,0.904,5,-2.729,1,0.0618,0.1930,0.000000,0.0640,0.681,82.014,rock,3.182433
1990,Sam Smith,How Do You Sleep?,202204,False,2019,73,0.477,0.682,1,-4.931,0,0.0925,0.1530,0.000000,0.0763,0.345,110.567,pop,3.370067
1995,Jonas Brothers,Sucker,181026,False,2019,79,0.842,0.734,1,-5.065,0,0.0588,0.0427,0.000000,0.1060,0.952,137.958,pop,3.017100
1996,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707,1,0.1570,0.1170,0.000021,0.1050,0.564,169.994,pop,2.973767
1998,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513,1,0.0656,0.4500,0.000002,0.2220,0.347,102.998,pop,2.850483